import { Inter } from "next/font/google";
import "./globals.css";

import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, searchParams }) {
  const gtmId = headers().get("X-Gtm-Id");

  return (
    <html lang="en">
      <head>
        <meta
          name="adopt-website-id"
          content="8ce6f54f-4561-40cb-b614-a9482142d037"
        />
        <script
          src="//tag.goadopt.io/injector.js?website_code=8ce6f54f-4561-40cb-b614-a9482142d037"
          className="adopt-injector"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                })(window,document,'script','dataLayer', "${gtmId}");
              `,
          }}
        ></script>
      </head>
      <body className={inter.className}>
        <noscript>
          <iframe
            src={`https://www.googletagmanager.com/ns.html?id=${gtmId}`}
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        {children}
      </body>
    </html>
  );
}
